theme: af-generic

plugins:
  - jekyll-data

title: "Direkt"
description: "iOS Navigation library written in Swift"

baseURL: "https://appfoundry.github.io/direkt/"

logo:
  brand:
    name: "Direkt"
    punchline: "iOS Navigation library written in Swift"
  svgId: ""
  pngFile: "direkt_logo.png"

headerImage: "direkt_logo.png"
